### ISSUE TITLE
Botões share de redes socias

### ISSUE THREAD

**Issue by mvfsilva** [lucasmaiaesilva/lucasmaiaesilva.github.io#3]
Você está usando SVG ou Font Awesome Icons?

**Comment by lucasmaiaesilva** [comment]
To usando imagens em PNG por enquanto

**Comment by mvfsilva** [comment]
As imagens estão no projeto?

**Comment by lucasmaiaesilva** [comment]
Só as imagens em PNG, depois eu vou subir as imagens em SVG tb
Em 16/10/2015 11:22 PM, "Marcus Silva" <notifications@github.com> escreveu:

**Comment by mvfsilva** [comment]
Beleza!
